### ISSUE TITLE
Android Hiltを導入したことによりクラッシュが発生する

### ISSUE THREAD

**Issue by wf9a5m75** [wf9a5m75/WeatherApp#5]
## 症状

アプリを2回目以降に起動後、クラッシュする

## エラー発生箇所
https://github.com/wf9a5m75/WeatherApp/blob/4d640f7f02304dcd4d0904a898c49c16c64e6314/android/app/src/main/java/com/example/weatherapp/model/AppViewModel.kt#L38

## ログ

```Process: com.example.weatherapp, PID: 20439
java.lang.IllegalStateException: Reading a state that was created after the snapshot was taken or in a snapshot that has not yet been applied
	at androidx.compose.runtime.snapshots.SnapshotKt.readError(Snapshot.kt:1857)
	at androidx.compose.runtime.snapshots.SnapshotKt.readable(Snapshot.kt:1842)
	at androidx.compose.runtime.SnapshotMutableStateImpl.getValue(SnapshotState.kt:130)
	at com.example.weatherapp.model.AppViewModel$loadSelectedCity$1.invokeSuspend(AppViewModel.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b62407b, Dispatchers.IO]

```

**Comment by wf9a5m75** [comment]
withContext([Dispatcher.IO])　が悪かったみたい。
https://issuetracker.google.com/issues/166486000#comment2
